@testable import Platform
import XCTest

final class ExclusionRulesTests: XCTestCase {
    func testConcealedUTIBlocks() {
        let rules = ExclusionRules()
        XCTAssertTrue(rules.shouldExclude(types: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text"], appBundleID: "com.example"))
    }

    func testAppBundleIDBlocks() {
        let rules = ExclusionRules(blockedBundleIDs: ["com.agilebits.onepassword7"])
        XCTAssertTrue(rules.shouldExclude(types: ["public.utf8-plain-text"], appBundleID: "com.agilebits.onepassword7"))
    }

    func testNonBlockedAllowed() {
        let rules = ExclusionRules()
        XCTAssertFalse(rules.shouldExclude(types: ["public.utf8-plain-text"], appBundleID: "com.example"))
    }

    func testNilBundleIDIsAllowed() {
        let rules = ExclusionRules()
        XCTAssertFalse(rules.shouldExclude(types: ["public.utf8-plain-text"], appBundleID: nil))
    }

    func testExcludesTransientType() {
        let rules = ExclusionRules(transientUTIs: ["org.nspasteboard.TransientType"])
        XCTAssertTrue(rules.shouldExclude(types: ["org.nspasteboard.TransientType"], appBundleID: nil))
    }

    func testDefaultRulesExcludeGeneratedAndKnownConfidentialPasteboardTypes() {
        let rules = ExclusionRules()

        XCTAssertTrue(rules.shouldExclude(types: ["org.nspasteboard.AutoGeneratedType"], appBundleID: nil))
        XCTAssertTrue(rules.shouldExclude(types: ["com.agilebits.onepassword"], appBundleID: nil))
        XCTAssertTrue(rules.shouldExclude(types: ["de.petermaurer.TransientPasteboardType"], appBundleID: nil))
        XCTAssertTrue(rules.shouldExclude(types: ["Pasteboard generator type"], appBundleID: nil))
    }

    func testExcludesViaRegex() {
        let rules = ExclusionRules(
            blockedBundleIDs: [],
            regexBlocklist: RegexBlocklist(patterns: [#"^secret-"#])
        )
        XCTAssertTrue(rules.shouldExcludeText("secret-token"))
        XCTAssertFalse(rules.shouldExcludeText("public-token"))
    }
}
